/**
 * generated by Xtext 2.17.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Subtraction</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSubtraction()
 * @model
 * @generated
 */
public interface Subtraction extends Command
{
} // Subtraction
